# fly.toml app configuration file generated for infamous-freight on 2026-01-26T23:50:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "infamous-freight-as-3gw"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  API_PORT = "3001"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
