// Single source of truth for routes that should bypass the authenticated app layout.
// AppLayout reads PUBLIC_PATH_PREFIXES to skip the auth gate; App.tsx mounts these
// outside of <AppLayout /> so they render with no chrome.
export const PUBLIC_PATH_PREFIXES = [
  '/',
  '/about',
  '/case-studies',
  '/carrier-agreement',
  '/login',
  '/register',
  '/onboarding',
  '/contact',
  '/track',
  '/track-shipment',
  '/tracking',
  '/home',
  '/request-quote',
  '/customer-portal',
  '/carrier-portal',
  '/freight-assistant',
  '/services',
  '/pricing',
  '/partners',
  '/drive',
  '/drivers',
  '/faq',
  '/gdpr',
  '/graphhopper',
  '/load-board',
  '/privacy',
  '/product-hunt',
  '/resources',
  '/shipment',
  '/shipper-agreement',
  '/terms',
  '/thank-you',
] as const;

export const PUBLIC_PATHS: ReadonlySet<string> = new Set([
  '/',
  '/about',
  '/case-studies',
  '/carrier-agreement',
  '/contact',
  '/login',
  '/register',
  '/onboarding',
  '/home',
  '/request-quote',
  '/track-shipment',
  '/tracking',
  '/customer-portal',
  '/carrier-portal',
  '/freight-assistant',
  '/services',
  '/pricing',
  '/partners',
  '/drive',
  '/drivers',
  '/faq',
  '/gdpr',
  '/graphhopper',
  '/load-board',
  '/privacy',
  '/product-hunt',
  '/resources',
  '/shipper-agreement',
  '/terms',
  '/thank-you',
]);

export function isPublicPath(pathname: string): boolean {
  if (pathname === '/') return true;
  return PUBLIC_PATH_PREFIXES.filter((p) => p !== '/').some((p) => pathname === p || pathname.startsWith(`${p}/`));
}
